# Generated by Django 5.2 on 2025-04-29 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='nba_api_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='nba_api_id',
        ),
    ]
