# Generated by Django 5.2 on 2025-04-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0002_remove_player_nba_api_id_remove_team_nba_api_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AddField(
            model_name='player',
            name='team_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
