# Generated by Django 5.2 on 2025-04-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
